export enum WebSocketEvent {
  UserAddedToTeam = "user_added_to_team",
  UserRemovedFromTeam = "user_removed_from_team",
  UserAddedToGroup = "user_added_to_group",
  UserRemovedFromGroup = "user_removed_from_group",
  UserAddedToMeeting = "user_added_to_meeting",
  UserRemovedFromMeeting = "user_removed_from_meeting",
  UserAddedAsFriend = "user_added_as_friend",
  UserRemovedAsFriend = "user_removed_as_friend",
  TeamCreated = "team_created",
  MeetingCreated = "meeting_created",
  GroupCreated = "group_created",
  FriendMessageCreated = "friend_message_created",
  GroupMessageCreated = "group_message_created",
  MeetingMessageCreated = "meeting_message_created",
}
