export enum KeyPrefixV2 {
  User = "user_",
  Organization = "org_",
  Team = "team_",
  Group = "group_",
  Meeting = "meeting_",
  OneOnOne = "one_on_one_",
  Message = "message_",
  ReplyTo = "reply_to_",
  Email = "email_",
  Phone = "phone_",
  Username = "username_",
  Active = "active_",
  Created = "created_",
  Due = "due_",
  Agenda = "agenda_",
}
