name: Run Unit Tests

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Bootstrap
        run: npx lerna bootstrap
      - name: Build Util
        run: yarn workspace @yac/util build:library
      - name: Build Other Services
        run: npx lerna run build:dev
      - name: Test
        run: yarn test:unit
        
