name: Run Unit Tests

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.x'
      - name: Install Dependencies
        run: yarn
      - name: Bootstrap
        run: npx lerna bootstrap
      - name: Build Services
        run: lerna run build --parallel --ignore @yac/pipeline
      - name: Test
        run: yarn test:unit
        
